#!/usr/bin/env bash

xkb() {
  setxkbmap -option &&
  setxkbmap -option caps:escape && 
  [[ "$1" == "-swap" ]] && setxkbmap -option altwin:swap_alt_win;
}

exterminate() { 
  for process in "$@"; do
    ps xu | grep -v grep | grep "$process" | awk '{ print $2 }' | xargs -r kill
  done
}

xmonad() {
  if [[ "$1" == "--restart" ]]; then
    exterminate "status.sh" "dzen" 
    "$HOME/.cabal/bin/xmonad" --restart;
  else
    "$HOME/.cabal/bin/xmonad" "$@";
  fi
}

wallpaper() {
  local resolution="$1"
  local wallpaper="sleep_of_reason.jpg"
  feh --bg-fill "$HOME/usr/share/wallpapers/$resolution/$wallpaper"
}

monitor() {
  xrandr --output default "$@";
}

case "$1" in
  room)
    xkb -swap; 
    monitor --mode "1024x768";
    wallpaper "1366x768";
    xmonad --restart;
    ;;
  office)
    xkb -swap; 
    monitor --mode "1920x1080";
    wallpaper "1920x1080";
    xmonad --restart;
    ;;
  lap)
    xkb; 
    monitor --mode "1366x768";
    wallpaper "1366x768";
    xmonad --restart;
    ;;
  *)
    echo "$0 lap|room|office";
esac
