#!/usr/bin/env bash
# big: giant readable notifications for presentations and cross-room silent shouts

function require()
{ # Evaluate a command as a dependency.
  type "$1" &> /dev/null || return 1;
}

abort() { 
  echo "$1"
  exit 1 
}

require 'dzen2' || abort "Requires dzen2"

MAX_X=$(xrandr | awk '{if (NR==1) {print $8}}')
MAX_Y=$(xrandr | awk '{if (NR==1) {print $10}}' | tr -d ,)

FONT="Envy Code R:size=44"
HEIGHT="$MAX_Y"
WIDTH="$MAX_X"
BG="#fdf6e3"
FG="#839496"

X_POS="$((($MAX_X - $WIDTH)/2))"
Y_POS="$((($MAX_Y - $HEIGHT)/2))"

cat - | dzen2 -fn "$FONT" -x $X_POS -y $Y_POS -w $WIDTH -h $HEIGHT -bg $BG -fg $FG -p
