#!/usr/bin/env bash

xkb() {
  setxkbmap -option &&
  setxkbmap -option caps:escape && 
  [[ "$1" == "-swap" ]] && setxkbmap -option altwin:swap_alt_win;
}

exterminate() { 
  for process in "$@"; do
    ps xu | grep -v grep | grep "$process" | awk '{ print $2 }' | xargs -r kill
  done
}

xmonad() {
  if [[ "$1" == "--restart" ]]; then
    exterminate "status.sh" "dzen" 
    "$HOME/.cabal/bin/xmonad" --restart;
  else
    "$HOME/.cabal/bin/xmonad" "$@";
  fi
}

wallpaper() {
  local resolution="$1"
  local wallpaper="sleep_of_reason.jpg"
  feh --bg-fill "$HOME/usr/share/wallpapers/$resolution/$wallpaper"
}

edp() {
  xrandr --output eDP1 "$@";
}

dp1() {
  xrandr --output DP1 "$@";
}

_dp1() {
  # intel drivers are borked, we must trick them
  local line="$(cvt $1 $2 | grep -i modeline | sed -r 's/^\w+//')"
  local mode="$(cut -d\  -f1 <<<$line)"
  xrandr --newmode $line
  xrandr --addmode "DP1" $mode
  xrandr --output "DP1" --mode $mode
} 

[[ "$0" == "bash" ]] && return

case "$1" in
  desk)
    xkb -swap; 
    _dp1 1920 1080;
    dp1 --primary;
    edp --auto --right-of DP1;
    wallpaper "1920x1080";
    xmonad --restart;
    ;;
  lap)
    xkb; 
    edp --mode "1366x768" --rotate normal;
    dp1 --off;
    wallpaper "1366x768";
    xmonad --restart;
    ;;
  *)
    echo "$0 [room|lap]";
    ;;
esac
