#!/usr/bin/env bash

xkb() {
  setxkbmap -option
  eval `grep setxkbmap ~/.xinitrc`
  [[ "$1" == "swap" ]] && setxkbmap -option altwin:swap_alt_win
}

exterminate() { 
  for process in "$@"; do
    ps xu | grep -v grep | grep "$process" | awk '{ print $2 }' | xargs -r kill
  done
}

xmonad() {
  if [[ "$1" == "--restart" ]]; then
    exterminate "status.sh" "dzen" 
    shift; "$HOME/.cabal/bin/xmonad" --restart $@;
  else
    "$HOME/.cabal/bin/xmonad" $@;
  fi
}

wallpaper() {
  local wallpaper="sleep_of_reason.jpg"
  for res in $@; do 
    echo -n "$HOME/usr/share/wallpapers/$res/$wallpaper "
  done | xargs feh --bg-fill
}

EDP() {
  xrandr --output eDP1 "$@";
}

DP1() {
  xrandr --output DP1 "$@";
}

[[ "$0" == "bash" ]] && return

if `xrandr | grep -qE '^DP1 connected'` ; then
  xkb -swap;
  DP1 --primary --auto;
  EDP --auto --right-of DP1;
  wallpaper '1920x1080' '1366x768';
  xmonad --restart;
else
  xkb; 
  EDP --auto --primary;
  DP1 --off;
  wallpaper '1366x768';
  xmonad --restart;
fi
