#!/usr/bin/env ruby

class PDF
  attr_accessor :filename  

  def initialize filename
    self.filename = filename
  end

  def select_pages list
    system "mogrify -density 300 -quality 100 #{filename}[#{list.join(?,)}]" 
  end

  def properties
    IO.popen("identify -verbose #{self.filename} 2>/dev/null").read
  end
end

class String
  def to_pages
    self.split(/^(?=[^\s])/m).map(&:to_page)
  end
  def to_page
    p = lambda { |s| self.match(/(?<=#{s}: )[^ ]+/)[0]}
    Page.new p.call('Scene'), p.call('Geometry').split(/[x+]/)[0..1].map(&:to_i).inject(&:*)
  end
end

class Page
  attr_accessor :number, :size
  def initialize number, size
    self.number = number
    self.size   = size 
  end
end

ARGV.each do |pdf|
  pdf    = PDF.new(pdf)
  pages  = pdf.properties.to_pages
  small  = pages.map(&:size).min 
  pdf.select_pages pages.select { |page| page.size == small }.map(&:number)
end
