#!/usr/bin/env bash
# Extract files from a compressed archive.

if [[ -f $1 ]]; then
  case $1 in
    *.tar.bz2) tar xjf $1     ;;
    *.tar.gz)  tar xzf $1     ;;
    *.bz2)     bunzip2 $1     ;;
    *.rar)     unrar x $1     ;;
    *.gz)      gunzip $1      ;;
    *.tar)     tar xf $1      ;;
    *.tbz2)    tar xjf $1     ;;
    *.tgz)     tar xzf $1     ;;
    *.zip)     unzip $1       ;;
    *)         echo "'$1' does not use a known archive format." ;;
  esac
else
    echo "'$1' is not a valid file."
fi
