#! /usr/bin/env zsh

#? Usage: fetch-intermediates [<cert>]
#?
#? This program reads an X509 certificate from <cert>, and displays all
#? AIA-described intermediates in its chain. If <cert> is not specified, 
#? it instead reads from standard input.

set -euf

[[ "$@" == "--help" ]] && { grep '^#?' "$0" | cut -c4-; exit; }

curl -s "$(openssl x509 -noout -text < "${1:-/dev/stdin}" | awk '/CA Issuers/{sub("^.*URI:","");print}')" | ifne openssl x509 -inform der | tee >(ifne $0)
