#!/usr/bin/env bash
# Make sure I can execute all of my personal scripts.

BIN="${BIN:-$HOME/bin}"

for SCRIPT in $BIN/*; do
  chmod u+x "$SCRIPT" || echo "Error rewriting the permissions of $SCRIPT."
done
