#!/usr/bin/env bash

Endpoint="https://api.github.com"

fail() {
  echo "$1" 2>&1 && exit 1
};

while getopts ':u: :p:' Option; do
  case $Option in
     u) Username="$OPTARG";;
     p) Password="$OPTARG";;
    \?) fail "Invalid option: -$OPTARG";;
     :) fail "-$OPTARG requires an argument.";;
  esac
done; shift $(($OPTIND-1));

while [[ -n "$Username" && -z "$Password" ]]; do
  echo -n "[$(basename $0)] password for $Username: " && read -s Password && echo &&
  curl -s -u "$Username:$Password" "$Endpoint" | grep -qi 'bad credentials' && Password=""
done; Curl="curl -s " && [[ -n "$Username" ]] && Curl="$Curl -u $Username:$Password";

listRepositories() {
  IsOrganisation="$($Curl "$Endpoint/orgs/$1" | grep -i 'not found')"
  if [[ -n $IsOrganisation && $1 == $Username ]]; then
    Path="user/repos"
  elif [[ -n $IsOrganisation ]]; then
    Path="users/$1/repos"
  else
    Path="orgs/$1/repos"
  fi; 
  $Curl $Endpoint/$Path?per_page=99999 | awk -F\" '/full_name/ {print $4}'
};

listRepositories "$1" | while read repository; do
  directory="${repository##*/}"; 
  if [[ -d "$directory" ]]; then
    cd "$directory" && git pull origin master && cd ..
  else
    git clone "git@github.com:$repository"
  fi
done
