#!/usr/bin/env bash
#$ eval `hag`

set -ue

# A forwarded 'gpg-agent' will retain only the passphrase, we need the
# (protected) secret key to do anything with it:

FP=0xFF6A253DC4DECDD2; gpg2 --list-secret-keys $FP 2>&1 >/dev/null || {
  ssh $USER@hydra.zalora.com sudo -iu deploy gpg2 --armor --export-secret-keys $FP | 
  gpg2 --import
};

# 'socat' must be available on the receiving end to relay messages to the
# 'gpg-agent' socket:

ssh $USER@hydra.zalora.com sudo -iu deploy "sh -c 'type -P socat >/dev/null || nix-env -i socat'"

# Where's the remote 'gpg-agent' socket?

RemoteSocketPath=$(ssh $USER@hydra.zalora.com sudo -iu deploy "sh -c 'cut -d: -f1 <<< \$GPG_AGENT_INFO'")

# We'll setup a local relay in GPG's home directory; should it already exist,
# kill any process with it open. After that, if it *still* exists, unlink it.

LocalSocketPath="$HOME/.gnupg/S.gpg-agent.forward"

[ -S "$LocalSocketPath" ] && { 
  lsof -t $LocalSocketPath | xargs --no-run-if-empty kill -HUP 
};

[ -S "$LocalSocketPath" ] && unlink "$LocalSocketPath"

# Socket communication is relayed to the agent running on Hydra:

coproc socat "UNIX-LISTEN:$LocalSocketPath,unlink-close,unlink-early,fork,reuseaddr" "EXEC:ssh $USER@hydra.zalora.com 'sudo -iu deploy socat STDIO UNIX-CONNECT:$RemoteSocketPath'"

# Finally, describe the local agent set-up:

echo "GPG_AGENT_INFO=$LocalSocketPath:1:1; export GPG_AGENT_INFO"
