#!/bin/sh

lsof -i @localhost:9020 || {
  ssh -f -NT -D 127.0.0.1:9020 vi@106.187.45.14 -p 7889
}; PID=$(lsof -t -i @localhost:9020)

PCC=$(mktemp); sed 's/^ *//' > $PCC <<EOF 
  [ProxyList]
  socks4 127.0.0.1 9020
EOF

proxychains4 -f $PCC $*; kill $PID; rm $PCC
