#!/usr/bin/env bash

source "$HOME/bin/lib/ssh"

if listing_matches? 'could not open a connection'; then
  echo "Either the daemon isn't running, or it hasn't been configured properly."
  eval `ssh-agent`
  echo "Let's try again."
  $0
else
  echo "The daemon is running, loading remaining identities (if any.)"
  missing_keys | awk '/^>/{print $2}' | xargs -r ssh-add
fi
