#!/usr/bin/env ruby
# Thriftier version of <https://github.com/mjdominus/util/blob/master/bin/mkpasswd>.

DICT="/usr/share/dict/cracklib-small"
puts File.read(DICT).split.reject { |w| w =~ /['\.]/ or w.length >= 8 }.shuffle[0..3].map { |w| w.capitalize }.join
