#!/usr/bin/env bash
#get related artists' tracks

related "$@" | sed 's/ http.*$//' | while read ar; do
  ftrack "$ar" | while read ln; do
    dl="$(grep -oP 'https?://[^ ]*'           <<<"$ln")"
    tr="$(grep -oP "(?<=$ar - ).+(?= https?)" <<<"$ln")"
    fn="$ar - $tr"
    case $dl in
      *youtube*)
        ( youtube-dl -x --audio-format mp3 --audio-quality 0 -o "$fn.%(ext)s" "$dl";
          id3v2 -a "$ar" -t "$tr" "$fn.mp3"
        ) &
      ;;
      *freedownloads*)
        # Assuming MP3 for now..
        ( wget -O"$fn.mp3" -c "$dl";
          id3v2 -a "$ar" -t "$tr" "$fn.mp3"
        ) &
      ;;
    esac
  done
done
