#!/usr/bin/env bash

#root()
[[ -d /mnt/usb0/home/ ]] \
  && ROOT=/mnt/usb0/home \
  || ROOT="$HOME"
ROOT="$ROOT/usr/share/music/."

#mode()
[[ "$1" == -s ]] \
  && { mode=shuf; shift; } \
  || mode=sort

find "$ROOT" -type f -print0 \
  | grep -Eazi "${@:-*}" \
  | grep -Eazi '\.(m4a|flac|mp3)$' \
  | $mode -z \
  | xargs -0 play 
