#! /usr/bin/env bash

#? Usage: persevere [<command>]
#?
#? This program executes <command> repeatedly in its calling environment,
#? desisting the first time it exits with a value of 0. It then rings the
#? system bell.

set -euf

[[ "$@" == "--help" ]] && { grep '^#?' "$0" | cut -c4-; exit; }

(false; while [[ $? -gt 0 ]]; do $@; done) && echo -e '\a'
