#!/usr/bin/env bash
# play music
  
mproperty() { 
  mutagen-inspect "$2" | awk -F= "/$1/ {print \$2}" | sed q
}

scrobble() {
  logfile="$HOME/var/log/music/play.log"
  (date +%s; track; artist; album; year) | tr '\n' $'\036' >> "$logfile"
}

true; for filename in "$@"; do
  [[ $? == 1 ]] && exit

  track  () { mproperty 'title|TIT2|nam'  "$filename"; }
  artist () { mproperty 'artist|TPE1|ART' "$filename"; }
  album  () { mproperty 'album|TALB|alb'  "$filename"; }
  year   () { mproperty 'date|TDRC|day'   "$filename"; }

  if test "$(track)" -a "$(artist)" -a "$(album)" -a "$(year)"; then
    echo "$(artist) - $(track)"
    scrobble 
  else
    echo "Unknown: $(basename "$filename")"
#   don't scrobble
  fi
  mplayer -really-quiet -novideo "$filename" 2>/dev/null
done
