#!/usr/bin/env bash

ALRM="$HOME/usr/share/sounds/alarm.mp3"

BEEP() {
  date "+%H:%M%t$1"
  mplayer "$ALRM" >&/dev/null 
}

POMO() {
  WRK=$((25*60))
  BEEP $1:WRK; sleep $WRK
  [[ $1 == 4 ]] && BRK=15 || BRK=5
  BEEP $1:BRK; sleep $((60*BRK))
}

[[ $0 == bash ]] && return

true; while [[ $? == 0 ]]; do
  seq 1 4 | xargs -L1 -IN bash --init-file $0 -ic 'POMO N'
done
