#!/usr/bin/env ruby 

require 'nestful'

class RDD
  def initialize url=ARGV[0]
    readability = "http://www.readability.com/api/shortener/v1/urls"
    @response = Nestful.post(readability, url: url).to_hash
  end

  def id
    @response['meta']['id']
  end
end

STDOUT.puts ['http://www.readability.com/articles/', RDD.new.id, '?readbar=1'].join
