#!/usr/bin/env node

var Krake     = require('krake');
var Spider    = new Krake({});
var seenNames = [];

function pageFromName (name) {
  var encName = encodeURIComponent(name);
  return ["http://www.last.fm", "music", encName].join('/');
};

function relatedArtists (name, retrieved) {
  Spider.scrape({ 
    url: pageFromName(name)
  , cols: 
      [ { desc: 'name'
        , sel: '//a[@class="similar-artist"]/div/div/span'
        }
      ]
  }).addListener('retrieved', retrieved);
};

function processRelatedResult (result) {
  var name = result['name'];
  var idnt = name.toLowerCase();
  if (seenNames.indexOf(idnt)==-1) {
    seenNames.push(idnt);
    console.log(name, pageFromName(name));
  } 
  return name;
};

process.argv.slice(2, process.argv.length).forEach(function(name) {
  processRelatedResult({name:name});
  relatedArtists(name, function(res) {
    relatedArtists( 
      processRelatedResult(res)
    , processRelatedResult
    );
  });
});

// vim:set ft=javascript:
