#!/usr/bin/env bash

case $1 in
  zathura)
    while read pdf; do
      zathura $pdf &
    done <~/.local/share/zathura/state 
  ;;
  surf)
    while read url; do
      surf $url &
    done <~/.surf/state
  ;;
esac
