#!/usr/bin/env bash

SUBJECT='Hack and Tell'
RECIPIENT=(events@hackerspace.sg)
CC=("zr@ivxenzirezn.pbz" "uraqel@vxv.sv" "pureawvr@tznvy.pbz")
SPONSOR="Kai Hendry"
DATE="$@"

decode() {
  rot13 <<< "$1"; # bad bots!
}

_cc() {
  for encoded in "${CC[@]}"; do
    echo -n "-c $(decode $encoded) "
  done
}

_date() {
  date -d"$DATE" '+%F'
}

mutt $(_cc) -s "$SUBJECT" "$RECIPIENT" <<EOM
Could we book the space on $(_date) for an event?

  Name: Hack and Tell
  Description: A show and tell for hackers.
  When: $(_date), 2030-2200
  Sponsor: $SPONSOR
EOM
