#!/usr/bin/env bash

if [[ -n  "$1" ]]; then
  echo -ne "\033]0;$(basename $0): $1\007"
  mplayer -playlist "http://somafm.com/startstream=$1.pls" 2>&1 | 
  awk -F"'" '/ICY/ { print $2 }'
else
  curl -s somafm.com |
  awk -F'"' '/cbshort/ { gsub("/",""); print $4 }' 
fi
