#!/usr/bin/env bash

loaded_keys() {
  ssh-add -l | grep -Po "$HOME/.ssh/id_[^\. ]*" | sort 
}

all_keys() {
  find $HOME/.ssh -name 'id_*'  | grep -Ev '.pub$' | sort
}

missing?() {
  diff <(loaded_keys) <(all_keys) | wc -l;
}

while ((`missing?`!=0)); do
  sleep 20
done

exit 0
