#! /usr/bin/env bash

#? Usage: temporary-iam-credentials [<mins>]
#?
#? This program consumes the AWS STS API's 'GetSessionToken' action to
#? generate temporary credentials to act on behalf of an existing AWS
#? account or IAM user. Long-term security credentials are expected to
#? be available from the calling environment via AWS CLI's standard
#? provider chain. Generated credentials are valid for <mins> minutes,
#? defaulting to fifteen when that argument is missing. Output consists
#? of their specification in environment variables that, when evaluated
#? in a POSIX-compatible shell, are sufficient to configure the AWS CLI.

set -euf
set -o pipefail

[[ "$@" == "--help" ]] && { grep '^#?' "$0" | cut -c4-; exit; }

aws sts get-session-token --duration-seconds $((${1:-15}*60)) | jq -r '.Credentials | [
  "export AWS_ACCESS_KEY_ID=\(.AccessKeyId|@sh)",
  "export AWS_SECRET_ACCESS_KEY=\(.SecretAccessKey|@sh)",
  "export AWS_SESSION_TOKEN=\(.SessionToken|@sh)"
][]'
