#!/usr/bin/env bash
#usage: `uf +2`; `uf -7`

# $1: a regex that'll matching the resource we're looking for.
getResource() {
  xrdb -query | awk -F"\t" "/$@/{print\$2}"
}

# $1: the adjustment to be made to the font's size.
adjustSpec() {
  a="$1"; shift
  sed -r "s/(.*size=)([0-9]+)(.*)/echo \1\$(bc<<<\2$a)\3/e" <<< "$@"
}

# $1: is the property's resource name.
# $2: is part of the property's `rxvt` escape sequence.
# $3: the adjustment to be made to the font size.
adjustFont() {
  x="$1"; r="$2"; a="$3"; 
  s="$(adjustSpec $a `getResource $x`)"
  printf '\33]%s;%s\007' "$r" "$s"
  xrdb -override <<< "URxvt*$x: $s"
};

[[ $0 == "bash" ]] && return

if [[ -n "$1" ]]; then
  adjustFont font       710 "$1"
  adjustFont boldFont   711 "$1"
  adjustFont italicFont 712 "$1"
fi
