#!/usr/bin/env ruby
# Anti-akrasic tool, reminds me of the number of hours until my actuarial death.

class Computer
  def in_use?
    system('pgrep slock &>/dev/null') ? false : true
  end
end

class XMessage
  attr_accessor :message, :display

  def initialize(message, display=':0')
    @message = message
    @display = display
  end

  def run
    if message
      system "xmessage -display #{@display} -buttons '' #{@message}" 
    end
  end
end

class Human
  %w|seconds hours minutes|.each do |unit|
    eval "attr_accessor :death_#{unit}"
  end

  def initialize death_second
    @death_seconds = death_second - Time.now.to_i
    @death_minutes = @death_seconds.fdiv(60).ceil
    @death_hours   = @death_minutes.fdiv(60).ceil
  end
end

# Seconds of my actuarial death.
# From [Death Clock](http://www.deathclock.com/).
vi = Human.new(3104524800)

if Computer.new.in_use? and rand(4).eql?(1)
  XMessage.new("#{vi.death_hours} hours to live. Is what you are doing important?").run
end
