#!/bin/bash

export DISPLAY=:0
export PATH=/usr/bin:$HOME/bin

property() {
  xwininfo -root -tree \
    | awk -F\" "/$1/{print \$1}" \
    | xargs -I{} xprop -id {} "$2" \
    | awk -F\" '$0!~/not found/{print $2}'
}; 

surf::urls() {
  property "Surf" "_SURF_URI"
}

surf::open() {
  psgrep ' surf ' &>/dev/null
}

zathura::open() {
  psgrep ' zathura ' &>/dev/null
};

zathura::files() {
  property "Zathura" "_ZATHURA_FILEPATH"
};


surf::open && (surf::urls > ~/.surf/state)
zathura::open && (zathura::files > ~/.local/share/zathura/state)
