#!/bin/bash

export DISPLAY=:0

surf::urls() {
  xwininfo -root -tree \
    | awk '/Surf/{print $1}' \
    | xargs -I{} xprop -id {} _SURF_URI \
    | grep -o 'http[^"]*'
};

surf::open() {
  psgrep ' surf ' &>/dev/null
}

zathura::open() {
  psgrep ' zathura ' &>/dev/null
};

zathura::files() {
  local h="$HOME/.local/share/zathura/history"
  xwininfo -root -tree \
    | awk -F\" '/home.*zathura/{print $2}'
};


surf::open && (surf::urls > ~/.surf/state)
zathura::open && (zathura::files > ~/.local/share/zathura/state)
