#!/usr/bin/env bash

locked() {
  ps aux | grep -v grep | grep -q slock
}

screen() {
  DISPLAY=':0' scrot -m "$@"
}

cam() {
  ffmpeg -f video4linux2 -s 640x480 -i /dev/video0 -t 1 -ss 00:00:01 -f mjpeg lol.jpg
}

if ! locked; then
  dir="$HOME/usr/share/cron/panopticon/$(date +%Y-%m-%d)"
  num="$(date +%H%M)"
  prefix="$dir/$num"

  [[ -d "$dir" ]] || mkdir -p "$dir"
  screen "${prefix}_screen.png"
  cam "${prefix}_cam.png"
fi
